language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/net-entreprise-micro.git"
  - secure: EkbT0cYWKRum/WWzMs96EEz6C7wNo4QLTyr3bmCks/CKpgNaSTnJr7HOQHrvRBigIm0N8qdQ1FozaMpYXsfLV/gXH6mR09+JIOqd8EqU4KWdlBgiXTVN7L7cmrCrY2CzWPc/oHldSPBohEPoEAFSNTMkFtQmF+fJrKAtt1ue8fqUbPB07gIghK0+1l4Tx7708jjCird1QDvlHo33OHOTdQFgcsvWCMO0I9zBCZ9ibsQ8E2awJbtHI+hKF2gtIgyL8rol8its9Byzc1gH3IqTu6Dnhp3/Oo7gJn8WKo4nBnVjYyguXmeN1Zx9nHei0zZ8Etakncv44682byRVlRG0p/j7EZTvFN0J1XZ0LzNTJXib8HRh+/VXP1GcHiJurz+Xz097zm90bhBZjLapc/JklPhG7cRaTdrUc1NRXoMrN7W1rkanIJgGz1j/QYt7z7RLkLAeOkCecpLuZR4TdyiDnYBytqDGssoPz1A1ySwBexCmdT4sTN9NlxCyvR3PSVV13iTg3pZzw6EhCvdMws54bHzKmstV6Oy/e3Wklqb5WttGISayD3KVvYL/oiPs4tbkClvqzasMHlnJy8vmt0HQmlYEuJCkM17B2CZgyqh+KfC3PjSC+t4SHkqiyhWX7w1jyNCgzR4kfcrh9Kr02DUp6EAcMrdgYCMvYS4Gtxsvdpc=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
- yarn run check
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_fb9d73f038c1_key -iv $encrypted_fb9d73f038c1_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
